"""Decomposition for cross-reaction matching.

This module produces `decomposed_uid_mapping` — the *plumbing* table used by
`find_best_reaction_match` to match a reaction's input combinations to its
output combinations. It is NOT the final logic network; that's
`logic_network.csv`, generated by `logic_network_generator`.

Two semantic rules drive this module. They look similar but are biologically
opposite — see docs/DESIGN_DECISIONS.md for the full discussion:

- **EntitySet** = any one of `{A, B, C}` plays this role. Decomposed to a flat
  set of alternatives so that matching across reactions can see through:
  R1 producing set `{A, B}` correctly links to R2 consuming free A.
- **Complex** = a bound species (e.g. an A:B dimer). Treated atomically by
  matching: R1 producing complex `A:B` does NOT link to R2 consuming free A.
  They're different species; getting free A from A:B requires a dissociation
  reaction that is its own pathway step.

The one place a Complex is decomposed here is when it contains an EntitySet
inside — then the cartesian product is needed so that each alternative
combination forms its own virtual reaction.

Anything you want to expose at the network level for perturbation (e.g.
breaking root/terminal complexes into their components) belongs in
`logic_network_generator`, not here. Adding more decomposition here will
create false links between unrelated species.
"""

import hashlib
import itertools
import os
import uuid
import warnings
from typing import Any, Dict, List, Optional, Sequence, Set, Tuple, Union

import pandas as pd

from src.argument_parser import logger
from src.best_reaction_match import find_best_reaction_match
from src.decomposed_uid_mapping import decomposed_uid_mapping_column_types
from src.neo4j_connector import (
    clear_prefetch_cache,
    get_complex_components,
    get_labels,
    get_reaction_input_output_ids,
    get_reference_entity_id,
    get_set_members,
    prefetch_entity_data,
)

warnings.filterwarnings(
    "ignore",
    message="The behavior of DataFrame concatenation with empty or all-NA entries is deprecated.",
    category=FutureWarning,
)

# Define types
UID = str
ComponentID = str
InputOutputID = str
ReactomeID = str
DataFrameRow = Dict[str, Any]

# Cap on set-variant cartesian expansion (issue #40). When a complex's internal
# EntitySet combinations — or a reaction's input/output combinations — would
# exceed this, we bundle all alternatives into ONE opaque node instead of
# materializing the full product. This prevents catalog-scale explosions
# (Class_I_MHC = 3.3M edges, Chromatin_modifying_enzymes = 1.4M) and the hangs
# they cause, at the cost of not set-splitting a handful of pathologically large
# assemblies. Env-tunable via LNG_MAX_VARIANTS; <= 0 disables the cap.
MAX_VARIANTS = int(os.environ.get("LNG_MAX_VARIANTS", "512"))

class _DecompositionStore:
    """Append-mostly buffer for decomposition rows with O(1) lookups.

    This used to be a pandas DataFrame that grew via repeated
    pd.concat — which is O(N) per call and made decomposition
    O(N²) in total rows. Profiling showed pd.concat dominating
    runtime (44% of Autophagy at ~12s of 28s; vastly more on big
    pathways like Cell_Cycle which took ~4 hours).

    Now the rows live in a Python list, with two side-indexes
    (uid → row indices, reactome_id → row indices) that the hot
    lookups in break_apart_entity and friends use. The pandas
    DataFrame is built exactly once, at the end of decomposition,
    when get_decomposed_uid_mapping returns.
    """

    def __init__(self) -> None:
        self._rows: List[DataFrameRow] = []
        self._by_uid: Dict[str, List[int]] = {}
        self._by_reactome_id: Dict[str, List[int]] = {}

    def clear(self) -> None:
        self._rows.clear()
        self._by_uid.clear()
        self._by_reactome_id.clear()

    def add(self, row: DataFrameRow) -> None:
        idx = len(self._rows)
        self._rows.append(row)
        uid = row.get("uid")
        if uid is not None and not pd.isna(uid):
            self._by_uid.setdefault(uid, []).append(idx)
        rid = row.get("reactome_id")
        if rid is not None and not pd.isna(rid):
            self._by_reactome_id.setdefault(rid, []).append(idx)

    def add_many(self, rows: List[DataFrameRow]) -> None:
        for row in rows:
            self.add(row)

    def rows_by_uid(self, uid: str) -> List[DataFrameRow]:
        return [self._rows[i] for i in self._by_uid.get(uid, [])]

    def rows_by_reactome_id(self, reactome_id: str) -> List[DataFrameRow]:
        return [self._rows[i] for i in self._by_reactome_id.get(reactome_id, [])]

    def has_reactome_id(self, reactome_id: str) -> bool:
        return reactome_id in self._by_reactome_id

    def __len__(self) -> int:
        return len(self._rows)

    @property
    def empty(self) -> bool:
        return not self._rows

    def to_dataframe(self) -> pd.DataFrame:
        df = pd.DataFrame(self._rows, columns=list(decomposed_uid_mapping_column_types.keys()))
        return df.astype(decomposed_uid_mapping_column_types)

    def dataframe_for_uids(self, uids: Set[str]) -> pd.DataFrame:
        """Build a small DataFrame containing only rows for the given UIDs.

        Used by find_best_reaction_match — it only needs to look up
        component_id_or_reference_entity_id by uid for a handful of
        combinations, so building a per-reaction slice is cheap and
        avoids materializing the full table mid-decomposition.
        """
        rows: List[DataFrameRow] = []
        for uid in uids:
            rows.extend(self.rows_by_uid(uid))
        return pd.DataFrame(rows, columns=list(decomposed_uid_mapping_column_types.keys()))


_store = _DecompositionStore()

reference_entity_dict: Dict[str, str] = {}

# Cache for complex EntitySet checking to avoid repeated database queries
_complex_contains_set_cache: Dict[str, bool] = {}

# Stoichiometry tracking: maps entity_id → {returned_uid_or_id: stoichiometry}
# Populated during break_apart_entity for Complex decomposition,
# consumed by get_broken_apart_ids to set per-row stoichiometry.
_direct_component_stoichiometry: Dict[str, Dict[str, int]] = {}

# Skip ubiquitin EntitySets - all members (UBB, UBC, RPS27A, UBA52)
# encode the same 76-amino-acid protein, so decomposing adds no
# biological insight and causes combinatorial explosion.
_UBIQUITIN_ENTITY_SET_IDS = {
    "R-HSA-68524",    # Ub [nucleoplasm]
    "R-HSA-113595",   # Ub [cytosol]
    "R-HSA-8943136",  # Ub [endoplasmic reticulum membrane]
    "R-HSA-9660032",  # Ub [late endosome lumen]
    "R-HSA-9660007",  # Ub [lysosomal lumen]
    "R-HSA-9834963",  # Ub [mitochondrial outer membrane]
}


def get_component_id_or_reference_entity_id(reactome_id: str) -> str:
    """Get the reference entity ID for a Reactome stable ID, with caching.

    Args:
        reactome_id: Reactome stable ID for the entity (e.g., "R-HSA-12345")

    Returns:
        Reference entity stable ID if it exists, otherwise the reactome_id
    """
    global reference_entity_dict

    if reactome_id in reference_entity_dict:
        component_id = reference_entity_dict[reactome_id]
        return component_id

    reference_entity_id = get_reference_entity_id(reactome_id)

    reference_entity_dict[reactome_id] = (
        reference_entity_id if reference_entity_id else reactome_id
    )

    return reference_entity_dict[reactome_id]


def is_valid_uuid(identifier: Any) -> bool:
    """Check if the given value is a valid UUID (64-character hash).

    Args:
        identifier: Value to check

    Returns:
        True if identifier is a 64-character string, False otherwise
    """
    if not isinstance(identifier, str):
        return False
    return len(identifier) == 64


def get_broken_apart_ids(
    broken_apart_members: Sequence[Union[Set[str], str]],
    reactome_id: ReactomeID,
    source_entity_id: Optional[str] = None
) -> Set[UID]:
    """Get broken apart IDs."""
    if not broken_apart_members:
        logger.debug(f"Empty broken_apart_members for reaction {reactome_id}, returning empty set")
        return set()

    uids: Set[UID]
    if any(isinstance(member, set) for member in broken_apart_members):
        new_broken_apart_members: List[Set[str]] = []
        for member in broken_apart_members:
            if isinstance(member, set):
                new_broken_apart_members.append(member)
            else:
                new_broken_apart_members.append({member})

        cartesian_size = 1
        for member in new_broken_apart_members:
            cartesian_size *= max(1, len(member))
        if MAX_VARIANTS > 0 and cartesian_size > MAX_VARIANTS:
            # Too many set-variant combinations (issue #40): bundle every
            # alternative into a single opaque node rather than exploding.
            merged: Set[str] = set()
            for member in new_broken_apart_members:
                merged |= member
            logger.warning(
                f"variant cap hit for {reactome_id}: {cartesian_size} "
                f"combinations > {MAX_VARIANTS}; bundling "
                f"{len(new_broken_apart_members)} components into one node"
            )
            uids = get_uids_for_iterproduct_components(
                [merged], reactome_id, source_entity_id
            )
        else:
            iterproduct_components = list(itertools.product(*new_broken_apart_members))
            iterproduct_components_as_sets = [
                set(map(str, item)) for item in iterproduct_components
            ]
            uids = get_uids_for_iterproduct_components(
                iterproduct_components_as_sets, reactome_id, source_entity_id
            )
    else:
        uid = str(uuid.uuid4())
        rows: List[DataFrameRow] = []
        stoich_lookup = _direct_component_stoichiometry.get(reactome_id, {})
        for flat_member in broken_apart_members:
            assert isinstance(flat_member, str), (
                "All-strings branch reached with a non-string member"
            )
            member_stoich = stoich_lookup.get(flat_member, 1)
            if is_valid_uuid(flat_member):
                for prev_row in _store.rows_by_uid(flat_member):
                    rows.append({
                        "uid": uid,
                        "component_id": prev_row["component_id"],
                        "reactome_id": reactome_id,
                        "component_id_or_reference_entity_id": get_component_id_or_reference_entity_id(
                            prev_row["component_id"]
                        ),
                        "input_or_output_uid": flat_member,
                        "input_or_output_reactome_id": None,
                        "source_entity_id": source_entity_id,
                        "source_reaction_id": None,
                        "stoichiometry": member_stoich,
                    })
            else:
                rows.append({
                    "uid": uid,
                    "component_id": flat_member,
                    "reactome_id": reactome_id,
                    "component_id_or_reference_entity_id": get_component_id_or_reference_entity_id(
                        flat_member
                    ),
                    "input_or_output_uid": None,
                    "input_or_output_reactome_id": flat_member,
                    "source_entity_id": source_entity_id,
                    "source_reaction_id": None,
                    "stoichiometry": member_stoich,
                })
        uids = {uid}
        _store.add_many(rows)

    return uids


def get_uids_for_iterproduct_components(
    iterproduct_components: List[Set[ComponentID]],
    reactome_id: ReactomeID,
    source_entity_id: Optional[str] = None
) -> Set[UID]:
    """Get UID for iterproduct components."""
    uids: Set[UID] = set()
    stoich_lookup = _direct_component_stoichiometry.get(reactome_id, {})
    for component in iterproduct_components:
        component_to_input_or_output: Dict[ComponentID, InputOutputID] = {}
        for item in component:
            if is_valid_uuid(item):
                for prev_row in _store.rows_by_uid(item):
                    component_to_input_or_output[prev_row["component_id"]] = item
            else:
                component_to_input_or_output[item] = item

        uid = hashlib.sha256(
            str(sorted(component_to_input_or_output.values())).encode()
        ).hexdigest()

        for component_id, input_or_output_id in component_to_input_or_output.items():
            input_or_output_uid = (
                input_or_output_id if is_valid_uuid(input_or_output_id) else None
            )
            input_or_output_reactome_id = (
                input_or_output_id if not is_valid_uuid(input_or_output_id) else None
            )
            item_stoich = stoich_lookup.get(input_or_output_id, 1)
            _store.add({
                "uid": uid,
                "component_id": component_id,
                "reactome_id": reactome_id,
                "component_id_or_reference_entity_id": get_component_id_or_reference_entity_id(
                    component_id
                ),
                "input_or_output_uid": input_or_output_uid,
                "input_or_output_reactome_id": input_or_output_reactome_id,
                "source_entity_id": source_entity_id,
                "source_reaction_id": None,
                "stoichiometry": item_stoich,
            })
        uids.add(uid)

    return uids


def _complex_contains_entity_set(entity_id: str) -> bool:
    """Check if a complex contains any EntitySet members (recursively).

    EntitySets represent alternatives (e.g., "any of these proteins"), which
    creates combinatorial complexity that must be decomposed. Simple complexes
    without EntitySets should remain as single entities.

    Args:
        entity_id: Reactome ID of the complex to check

    Returns:
        True if the complex contains any EntitySet members (recursively), False otherwise
    """
    global _complex_contains_set_cache

    # Check cache first
    if entity_id in _complex_contains_set_cache:
        return _complex_contains_set_cache[entity_id]

    labels = get_labels(entity_id)

    # If this entity itself is an EntitySet, return True
    if "EntitySet" in labels:
        _complex_contains_set_cache[entity_id] = True
        return True

    # If it's a complex, check its components recursively
    if "Complex" in labels:
        member_ids = get_complex_components(entity_id)
        for member_id in member_ids:
            if _complex_contains_entity_set(member_id):
                _complex_contains_set_cache[entity_id] = True
                return True

    _complex_contains_set_cache[entity_id] = False
    return False


def _emit_entityset_provenance_rows(entity_set_id: str, leaves: Set[str]) -> None:
    """Write rows that record EntitySet membership for each decomposed leaf.

    Each row's source_entity_id points back at the EntitySet, so a query like
    "which EntitySets contain leaf X?" can be answered by filtering
    decomposed_uid_mapping on (component_id == X) & source_entity_id.notna().

    The uid is a deterministic sha256 of (entity_set_id, leaf, component_id),
    which guarantees we don't write duplicates if this code is somehow invoked
    twice for the same EntitySet (the cache check at the top of
    break_apart_entity should already prevent this, but a deterministic uid is
    a belt-and-suspenders safeguard).

    Provenance uids are never returned upward from break_apart_entity, so
    downstream callers (best_reaction_match, _build_uid_index, etc.) never
    pass them in lookups — they live in the table purely as records.
    """
    if not leaves:
        return

    rows: List[DataFrameRow] = []
    for leaf in leaves:
        if is_valid_uuid(leaf):
            # Leaf is itself a UID from a nested decomposition (e.g., a
            # Complex inside this set). Expand to its component_ids and
            # record one provenance row per component.
            component_ids = sorted({r["component_id"] for r in _store.rows_by_uid(leaf)})
            for component_id in component_ids:
                rows.append({
                    "uid": hashlib.sha256(
                        f"{entity_set_id}|{leaf}|{component_id}".encode()
                    ).hexdigest(),
                    "component_id": component_id,
                    "reactome_id": entity_set_id,
                    "component_id_or_reference_entity_id":
                        get_component_id_or_reference_entity_id(component_id),
                    "input_or_output_uid": leaf,
                    "input_or_output_reactome_id": None,
                    "source_entity_id": entity_set_id,
                    "source_reaction_id": None,
                    "stoichiometry": 1,
                })
        else:
            rows.append({
                "uid": hashlib.sha256(
                    f"{entity_set_id}|{leaf}".encode()
                ).hexdigest(),
                "component_id": leaf,
                "reactome_id": entity_set_id,
                "component_id_or_reference_entity_id":
                    get_component_id_or_reference_entity_id(leaf),
                "input_or_output_uid": None,
                "input_or_output_reactome_id": leaf,
                "source_entity_id": entity_set_id,
                "source_reaction_id": None,
                "stoichiometry": 1,
            })

    _store.add_many(rows)


def get_terminal_components(entity_id: str) -> Set[str]:
    """Recursively walk a Complex/EntitySet structure down to its terminal leaves.

    Returns the set of leaf entity IDs (proteins, simple molecules, etc.)
    reachable from this entity. Used by `logic_network_generator` for the
    boundary-expansion pass: roots and terminals get synthetic assembly /
    dissociation edges to their leaves so individual proteins can be
    perturbed and read.

    This is a pure read — nothing is written to `decomposed_uid_mapping`.
    It is the *output-layer* counterpart to `break_apart_entity`'s
    matching-layer rules; the two intentionally treat Complexes
    differently (matching keeps them atomic; output decomposes them at
    boundaries). See docs/DESIGN_DECISIONS.md for the full discussion.
    """
    labels = get_labels(entity_id)
    if "Complex" in labels:
        components = get_complex_components(entity_id)
        leaves: Set[str] = set()
        for member_id in components:
            leaves |= get_terminal_components(member_id)
        return leaves if leaves else {str(entity_id)}
    if any(s in labels for s in ("EntitySet", "DefinedSet", "CandidateSet")):
        # Ubiquitin sets are atomic at the boundary too: decomposing them
        # would explode every boundary into ~14 indistinguishable copies.
        if entity_id in _UBIQUITIN_ENTITY_SET_IDS:
            return {str(entity_id)}
        members = get_set_members(entity_id)
        leaves = set()
        for member_id in members:
            leaves |= get_terminal_components(member_id)
        return leaves if leaves else {str(entity_id)}
    return {str(entity_id)}


def break_apart_entity(entity_id: str, source_entity_id: Optional[str] = None) -> Set[str]:
    """Break apart entity, tracking which parent entity it came from.

    This function decomposes entities based on the following rules:
    1. EntitySets: Always decompose (they represent alternatives)
    2. Complexes containing EntitySets: Decompose (to handle alternatives)
    3. Simple complexes (no EntitySets): Keep intact (return as single entity ID)
    4. Simple entities (proteins, molecules): Keep intact

    Args:
        entity_id: The Reactome entity ID to decompose
        source_entity_id: The parent entity (Complex or EntitySet) being decomposed

    Returns:
        Set of UIDs or entity IDs representing the decomposed entity

    The key change: Simple complexes are NO LONGER decomposed. This preserves
    intermediate complexes in the pathway, maintaining biological feedback loops.
    """
    labels = get_labels(entity_id)
    if "EntitySet" in labels or "Complex" in labels:
        cached = _store.rows_by_reactome_id(entity_id)
        if cached:
            leaves: Set[str] = set()
            for r in cached:
                v = r["input_or_output_uid"]
                if v is not None and not pd.isna(v):
                    leaves.add(v)
                v = r["input_or_output_reactome_id"]
                if v is not None and not pd.isna(v):
                    leaves.add(v)
            return leaves

    if "EntitySet" in labels:
        if entity_id in _UBIQUITIN_ENTITY_SET_IDS:
            return {str(entity_id)}

        member_ids = get_set_members(entity_id)

        # EntitySets represent OR alternatives - each member is a separate option
        # Return a flat set of all member IDs/UIDs (NOT a cartesian product)
        member_list: List[str] = []
        for member_id in member_ids:
            members = break_apart_entity(member_id, source_entity_id=entity_id)
            if isinstance(members, set):
                member_list.extend(members)
            else:
                member_list.extend(set(members))

        # Provenance: record each leaf's membership in this EntitySet so that
        # downstream callers can answer "which EntitySet does this leaf belong
        # to?" Without these rows, source_entity_id only ever surfaces in the
        # narrow Complex-containing-EntitySet path; bare-EntitySet inputs lose
        # their parent on the way back up to the reaction level.
        _emit_entityset_provenance_rows(entity_id, set(member_list))

        return set(member_list)

    elif "Complex" in labels:
        # NEW LOGIC: Only decompose complexes that contain EntitySets
        # Simple complexes (no sets) should remain as single entities
        if _complex_contains_entity_set(entity_id):
            # Complex contains EntitySets → decompose to handle alternatives
            logger.debug(f"Decomposing complex {entity_id} (contains EntitySet)")
            broken_apart_members: List[Set[str]] = []
            complex_components = get_complex_components(entity_id)

            for member_id in complex_components:
                stoich = complex_components[member_id]
                # Pass through the parent EntitySet ID when decomposing complex components
                members = break_apart_entity(member_id, source_entity_id=source_entity_id)
                broken_apart_members.append(members)
                # Track stoichiometry for each returned UID/ID within this Complex
                for uid_or_id in members:
                    _direct_component_stoichiometry.setdefault(str(entity_id), {})[uid_or_id] = stoich

            return get_broken_apart_ids(broken_apart_members, str(entity_id), source_entity_id)
        else:
            # Simple complex (no EntitySets) → keep as single entity
            logger.debug(f"Keeping complex {entity_id} intact (no EntitySets)")
            return {str(entity_id)}

    elif any(
        entity_label in labels
        for entity_label in [
            "Cell",
            "ChemicalDrug",
            "Drug",
            "EntityWithAccessionedSequence",
            "GenomeEncodedEntity",
            "OtherEntity",
            "Polymer",
            "SimpleEntity",
        ]
    ):

        return {str(entity_id)}

    else:
        # Unknown label type - treat as simple entity and continue
        logger.warning(f"Unknown entity labels for {entity_id}: {labels}. Treating as simple entity.")
        return {str(entity_id)}


def decompose_by_reactions(reaction_ids: List[str]) -> List[Any]:
    """Decompose by reactions."""
    logger.debug("Decomposing reactions")

    # Each best_match is a triple (input_hash, output_hash, reaction_id).
    # Without the reaction_id, create_reaction_id_map has to reverse-derive
    # it from the hash, which is ambiguous: the same hash can appear under
    # multiple reactome_ids in decomposed_uid_mapping (hashes are computed
    # from sorted components, not reactions).
    all_best_matches: List[tuple] = []
    for reaction_id in reaction_ids:
        input_ids = get_reaction_input_output_ids(reaction_id, "input")
        broken_apart_input_id = [break_apart_entity(input_id) for input_id in input_ids]
        input_combinations = get_broken_apart_ids(
            broken_apart_input_id, str(reaction_id)
        )

        output_ids = get_reaction_input_output_ids(reaction_id, "output")
        broken_apart_output_id = [
            break_apart_entity(output_id) for output_id in output_ids
        ]
        output_combinations = get_broken_apart_ids(
            broken_apart_output_id, str(reaction_id)
        )

        # Skip reactions with empty input or output combinations
        # This can happen when a reaction has no defined inputs or outputs in the database
        if not input_combinations or not output_combinations:
            logger.warning(
                f"Reaction {reaction_id} has empty {'inputs' if not input_combinations else 'outputs'}, skipping"
            )
            continue

        # Hand the matcher only the rows it actually needs, not the full
        # accumulated decomposition table. find_best_reaction_match looks
        # up component sets by uid, and the relevant uids are exactly the
        # input/output combinations of this reaction.
        mini_df = _store.dataframe_for_uids(input_combinations | output_combinations)
        [best_matches, _] = find_best_reaction_match(
            input_combinations, output_combinations, mini_df,
            reaction_id=reaction_id
        )

        # Tag each (input, output) pair with the reaction it came from
        # so downstream code doesn't have to reverse-derive it.
        all_best_matches.extend(
            (in_hash, out_hash, str(reaction_id)) for in_hash, out_hash in best_matches
        )

    return all_best_matches


def get_decomposed_uid_mapping(
    pathway_id: str, reaction_connections: pd.DataFrame
) -> Tuple[pd.DataFrame, List[Any]]:
    """Get decomposed UID mapping."""
    global reference_entity_dict, _complex_contains_set_cache
    global _direct_component_stoichiometry

    _store.clear()
    reference_entity_dict.clear()
    _complex_contains_set_cache.clear()
    _direct_component_stoichiometry.clear()
    clear_prefetch_cache()

    reaction_ids_arr = pd.unique(
        reaction_connections[
            ["preceding_reaction_id", "following_reaction_id"]
        ].values.ravel("K")
    )
    reaction_ids_arr = reaction_ids_arr[~pd.isna(reaction_ids_arr)]
    reaction_ids: List[str] = [str(r) for r in reaction_ids_arr]

    # Bulk pre-fetch all entity data from Neo4j (replaces thousands of individual queries)
    prefetch_entity_data(reaction_ids)

    best_matches = decompose_by_reactions(reaction_ids)

    # Materialize the DataFrame exactly once now that decomposition is done.
    # During decomposition all writes/reads went through _store (list +
    # dict indexes) instead of pd.concat, which dropped the per-row append
    # cost from O(N) to O(1).
    return (_store.to_dataframe(), best_matches)
